import builtins from 'builtin-modules'
import esbuild from 'esbuild'
import { readFileSync, copyFileSync, mkdirSync } from 'fs'
import process from 'process'
// import svgr from "esbuild-plugin-svgr";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const NODE_ENV = process.env.NODE_ENV
const prod = NODE_ENV === 'production'

const TLDRAW_VERSION = (() => {
	const json = JSON.parse(readFileSync(`${import.meta.dirname}/../../packages/tldraw/package.json`))
	return json.version
})()

const outdir = `${import.meta.dirname}/dist/${prod ? 'production' : 'development'}`

// Log specific build information about the build environment
console.log({
	prod,
	TLDRAW_VERSION,
	outdir,
	NODE_ENV: process.env.NODE_ENV
})


const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts', 'src/styles.css'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins,
	],
	format: 'cjs',
	target: 'es2023',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	loader: {
		'.js': 'jsx',
		'.woff2': 'dataurl',
		'.woff': 'dataurl',
		'.svg': 'file',
		'.png': 'file',
		'.json': 'file',
	},
	outdir,
	define: {
		TLDRAW_COMPONENT_LOGGING: `${!prod}`,
		MARKDOWN_POST_PROCESSING_LOGGING: `${!prod}`,
		TLDRAW_VERSION: `"${TLDRAW_VERSION}"`,
		// Workaround for import.meta in CommonJS builds
		'import.meta': JSON.stringify({
			env: {
				TLDRAW_LICENSE_KEY: process.env.TLDRAW_LICENSE_KEY || '',
			}
		}),
	},
	// plugins: [svgr({ typescript: true })],
	plugins: [
		{
			name: 'copy-plugin-manifest',
			setup(build) {
				build.onEnd(() => {
					const manifestSrc = `${import.meta.dirname}/manifest.json`
					const manifestDest = `${outdir}/manifest.json`
					console.log('Copying manifest.json from', manifestSrc, 'to', manifestDest)
					mkdirSync(outdir, { recursive: true })
					copyFileSync(manifestSrc, manifestDest)
				})
			}
		}
	]
})

if (prod) {
	await context.rebuild()
	process.exit(0)
} else {
	await context.watch()
}
